spring:
  http:
    encoding:
      charset: utf-8
      force: true
  datasource:
    druid:
      url: jdbc:oracle:thin:@localhost:1521:DGLOAN
      username: student
      #driver-class-name: oracle.jdbc.driver.OracleDriver
      password: Craffic
      driver-class-name: oracle.jdbc.OracleDriver
  kafka:
    bootstrap-servers: 192.168.1.104:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
    consumer:
      auto-commit-interval: 1S
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 5
      ack-mode: manual_immediate

server:
  port: 8081
  servlet:
    session:
      timeout: 1800
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.Craffic.myshop.domain.model


  application:
    name: myshop-mvc-service
# UserService service version
user:
  service:
    version: 1.0.0

# Dubbo Config properties
dubbo:
  ## Base packages to scan Dubbo Component：@com.alibaba.dubbo.config.annotation.Service
  scan:
    basePackages: com.Craffic.myshop.mvc.web.controller
  application:
    id: myshop-mvc-service
    name: myshop-mvc-service
    qos-port: 22222
    qos-enable: true
  protocol:
    id: dubbo
    name: dubbo
    port: 12345

  registry:
    id: zookeeper
    #address: zookeeper://192.168.1.103:2181?backup=192.168.1.103:2182,192.168.1.103:2183
    address: zookeeper://192.168.1.104:2181?backup=192.168.1.104:2182,192.168.1.104:2183

# Enables Dubbo All Endpoints
management:
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  # Dubbo Health
  health:
    dubbo:
      status:
        ## StatusChecker Name defaults (default : "memory", "load" )
        defaults: memory
        ## StatusChecker Name extras (default : empty )
        extras: load,threadpool
