spring:
  http:
    encoding:
      charset: utf-8
      force: true
  datasource:
    druid:
      url: jdbc:oracle:thin:@localhost:1521:DGLOAN
      username: student
      #driver-class-name: oracle.jdbc.driver.OracleDriver
      password: lipsadmins
      driver-class-name: oracle.jdbc.OracleDriver
server:
  port: 8081
  servlet:
    session:
      timeout: 1800
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.Craffic.myshop.domain.model
